# Stage 1: Build
FROM node:20-alpine AS builder
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL
ARG VITE_MSAL_ENABLED
ENV VITE_MSAL_ENABLED=$VITE_MSAL_ENABLED
ARG VITE_MSAL_CLIENT_ID
ENV VITE_MSAL_CLIENT_ID=$VITE_MSAL_CLIENT_ID
ARG VITE_MSAL_TENANT_ID
ENV VITE_MSAL_TENANT_ID=$VITE_MSAL_TENANT_ID
ARG VITE_MSAL_REDIRECT_URI
ENV VITE_MSAL_REDIRECT_URI=$VITE_MSAL_REDIRECT_URI
ARG VITE_MSAL_SCOPES
ENV VITE_MSAL_SCOPES=$VITE_MSAL_SCOPES
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build
# Stage 2: Serve
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
# Optional: custom nginx config for React Router support
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
